### ISSUE TITLE
iOS compile error after upgrading from 10.0.0 to 10.1.4

### ISSUE THREAD

**Issue by sjchristi** [maplibre/maplibre-react-native#811]
### Describe and reproduce the Bug

I'm still working on a reproduct, but wanted to check because I feel like I must just be doing something stupid with my upgrade.

Here's the error:

```
/Users/jojo/projects/my-react-project/node_modules/@maplibre/maplibre-react-native/ios/MLRN/MLRNVectorSource.m:7:41: error: no visible @interface for 'MLNVectorTileSource' declares the selector 'initWithIdentifier:configurationURLString:'
    7 |     return [[MLNVectorTileSource alloc] initWithIdentifier:self.id configurationURLString:self.url];
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Thet interface is clearly part of MLNVectorTileSource as far as I can tell..  it seems like xcode is just not downloading the right module?

Attempted a clean from xcode.  Nuked my node_modules and reinstalled them all.  No luck.

Any suggestions?

### @maplibre/maplibre-react-native Version

10.1.4

### Which platforms does this occur on?

iOS Simulator

### Which frameworks does this occur on?

Expo

### Which architectures does this occur on?

Old Architecture

### Environment

```text
expo-env-info 1.3.3 environment info:
    System:
      OS: macOS 15.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
      Yarn: 1.22.22 - ~/projects/ioverlander-client-react/node_modules/.bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
      Watchman: 20230430.125247.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.4, iOS 18.4, macOS 15.4, tvOS 18.4, visionOS 2.4, watchOS 11.4
      Android SDK:
        API Levels: 29, 30, 31, 33, 34, 35
        Build Tools: 29.0.3, 30.0.2, 30.0.3, 32.0.0, 33.0.1, 33.0.2, 34.0.0, 35.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-35 | Google APIs ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.3 AI-243.25659.59.2432.13423653
      Xcode: 16.3/16E140 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.46 => 52.0.46 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: ~0.77.2 => 0.77.2 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: bare
```

**Comment by sjchristi** [comment]
So..  a bit confused now, but I was rereading the actual header, and I noticed this:

```
- (instancetype)initWithIdentifier:(NSString *)identifier configurationURL:(NSURL *)configurationURL NS_DESIGNATED_INITIALIZER;
```

Whereas the source code here is:

```
  if (self.url != nil) {
    return [[MLNVectorTileSource alloc] initWithIdentifier:self.id configurationURLString:self.url];
  }
```

and self.url appears to be NSString, not NSURL

**Comment by sjchristi** [comment]
Appears to compile properly if I switch it to this:

```
      return [[MLNVectorTileSource alloc] initWithIdentifier:self.id configurationURL:[NSURL URLWithString:self.url]];
    //return [[MLNVectorTileSource alloc] initWithIdentifier:self.id configurationURLString:self.url];
```

Wondering if I have the right version of maplibre-native?  It's pulling in version 6.5 in my xcode project..  maybe that's the issue?

**Comment by KiwiKilian** [comment]
From MLRN 10.1.0 onwards the minimum iOS MLN version should be 6.10.0 due to https://github.com/maplibre/maplibre-react-native/pull/625.

**Comment by sjchristi** [comment]
Hmmm, I ran pod install several times but I suppose it didn't resolve this.

Is there a specific spot in the Podfile that sets this version number?  Hmmm.  Maybe some other part of my upgrade when bad and it's keeping around that old version.

**Comment by KiwiKilian** [comment]
Oh just notice you are using Expo. Then you'll have to run `expo prebuild` again or bump the native version manually within Xcode.

**Comment by sjchristi** [comment]
I'm running prebuild but not noticing anything change.  Maybe that's just an issue here on my side.  I'll try just manually updating xcode.  Thanks!

**Comment by KiwiKilian** [comment]
Maybe you could share your `Podfile`?

**Comment by sjchristi** [comment]
I manually updated our xcode project (not sure why expo prebuild wasn't updating it properly) and now it works fine!
